version: "3"
services:
  backend:
    image: bankaccount:latest
    container_name: backend
    ports:
      - 3080:8080
    restart: always
  
  postgres:
    image: postgres:14.4
    container_name: postgres
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=postgres
    restart: always
